#[cfg(any(feature = "google-ads-googleads-v15-common"))]
pub mod common;
#[cfg(any(feature = "google-ads-googleads-v15-enums"))]
pub mod enums;
#[cfg(any(feature = "google-ads-googleads-v15-errors"))]
pub mod errors;
#[cfg(any(feature = "google-ads-googleads-v15-resources"))]
pub mod resources;
#[cfg(any(feature = "google-ads-googleads-v15-services"))]
pub mod services;
