[package]
name = "xtask"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
toml_edit = "0.22.6"
prost-build = "0.12.3"
tonic-build = { version = "0.11.0", default-features = false, features = ["prost"] }
syn = "2.0.49"
prettyplease = "0.2.16"
