#[cfg(any(feature = "google-shopping-merchant-accounts-v1beta"))]
pub mod accounts;
#[cfg(any(feature = "google-shopping-merchant-conversions-v1beta"))]
pub mod conversions;
#[cfg(any(feature = "google-shopping-merchant-datasources-v1beta"))]
pub mod datasources;
#[cfg(any(feature = "google-shopping-merchant-inventories-v1beta"))]
pub mod inventories;
#[cfg(any(feature = "google-shopping-merchant-lfp-v1beta"))]
pub mod lfp;
#[cfg(any(feature = "google-shopping-merchant-notifications-v1beta"))]
pub mod notifications;
#[cfg(any(feature = "google-shopping-merchant-products-v1beta"))]
pub mod products;
#[cfg(any(feature = "google-shopping-merchant-promotions-v1beta"))]
pub mod promotions;
#[cfg(any(feature = "google-shopping-merchant-quota-v1beta"))]
pub mod quota;
#[cfg(any(feature = "google-shopping-merchant-reports-v1beta"))]
pub mod reports;
